---
- name: Update SSH config file
  tasks:
    - name: Edit config to add new ssh key
      become: true
      ansible.builtin.blockinfile:
        path: "/Users/{{ local_username }}/.ssh/config"
        # backup: yes
        block: |

          Host {{ master_node_public_ip }}
            AddKeysToAgent yes
            UseKeyChain yes
            IdentityFile {{ master_node_ssh_private_key }}
