resource "local_file" "ansible_vars_tf" {
  content  = <<-DOC
  # Ansible vars_file containing variable values from Terraform
  # Generated by Terraform

  local_username: ${var.local_admin_username}
  master_node_public_ip: ${var.dummy_ip_addr}
  master_node_ssh_private_key: ${local.private_key}
  DOC
  filename = "./ansible/vars/main.yml"
}

resource "ansible_host" "local" {
  name   = "127.0.0.1"
  groups = ["local"]
  variables = {
    ansible_connection  = "local"
    ansible_become_pass = var.local_admin_pass
  }
}

# resource "ansible_playbook" "local-update-ssh-config" {
#   playbook = "/Users/fiercebubble/Developer/Terraform/ansible-terraform/ansible/tasks/local-update-ssh-config.yaml"
#   name     = "127.0.0.1"
#   # replayable = true
#   verbosity = "6"
#   extra_vars = {
#     local_username              = var.local_admin_username
#     master_node_public_ip       = var.dummy_ip_addr
#     master_node_ssh_private_key = local.private_key
#   }
#   depends_on = [local_file.ansible_vars_tf]
# }


